"use client";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  const [open, setOpen] = useState(false);
  return (
    <div className="min-h-screen bg-[#f2f7fb] text-[#0f2440]">
      <style>{`@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}@keyframes pulse-ring{0%{transform:scale(0.8);opacity:1}100%{transform:scale(2.3);opacity:0}}.float-anim{animation:float 4s ease-in-out infinite}.float-anim2{animation:float 4s ease-in-out infinite 1s}.float-anim3{animation:float 4s ease-in-out infinite 2s}.pulse-ring::before{content:'';position:absolute;inset:0;border-radius:9999px;background:#25D366;animation:pulse-ring 2s infinite}`}</style>

      <header className="fixed top-0 w-full z-[100] bg-[#061e14] border-b border-white/10">
        <div className="max-w-[1240px] mx-auto px-5 h-[64px] flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5"><div className="w-8 h-8 bg-white rounded-full overflow-hidden flex items-center justify-center"><Image src="/logo.png" alt="GT" width={32} height={32} /></div><span className="text-white font-black tracking-widest">GTSERVIZ</span></Link>
          <nav className="hidden lg:flex gap-6 text-[13px] text-white/60"><Link href="#" className="text-[#00A54F] font-bold border-b-2 border-[#00A54F] py-5">Home</Link><Link href="#services" className="hover:text-white">Services</Link><Link href="#pricing" className="hover:text-white">Pricing</Link><Link href="#store" className="hover:text-white">Store</Link><Link href="#blog" className="hover:text-white">Blog</Link><Link href="#" className="hover:text-white">API</Link><Link href="#" className="hover:text-white">Reseller</Link></nav>
          <div className="hidden lg:flex gap-3"><Link href="/login" className="text-white text-[13px] px-4">Login</Link><Link href="/signup" className="px-5 py-2.5 rounded-full bg-[#00A54F] text-white text-[12px] font-black">Create Account</Link></div>
          <button onClick={()=>setOpen(!open)} className="lg:hidden w-10 h-10 rounded-full bg-white/10 text-white">{open?"✕":"☰"}</button>
        </div>
        {open && <div className="lg:hidden bg-[#0a2a1a] px-6 py-6 flex flex-col gap-4 text-white text-sm"><Link href="#">Home</Link><Link href="#services">Services</Link><Link href="#pricing">Pricing</Link><Link href="#store">Store</Link><Link href="#blog">Blog</Link><div className="flex gap-3 mt-3 pt-4 border-t border-white/10"><Link href="/login" className="flex-1 py-3 rounded-full border text-center">Login</Link><Link href="/signup" className="flex-1 py-3 rounded-full bg-[#00A54F] text-center font-black">Create Account</Link></div></div>}
      </header>

      <section className="bg-[#061e14] relative pt-[64px] overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#0e3320] to-[#061e14]" />
        <div className="max-w-[1240px] mx-auto px-5 py-12 md:py-20 grid md:grid-cols-2 gap-10 items-center relative z-10">
          <div className="text-center md:text-left"><div className="inline-flex px-3 py-1 rounded-full border border-[#00A54F]/40 bg-[#00A54F]/10 text-[#7cffb0] text-[10px] font-black">● FAST, CHEAP & SECURE</div><h1 className="text-white text-[32px] md:text-[50px] font-black leading-[1.05] mt-5">Fast, Cheap & Secure<br/>Airtime, Data, Cable TV<br/>and <span className="text-[#00A54F]">More!</span></h1><p className="text-white/60 text-[14px] mt-4 max-w-[420px] mx-auto md:mx-0">Top up airtime, buy data, pay bills, and more — instant, affordable, and reliable. All VTU services in one place.</p><div className="flex gap-3 mt-7 justify-center md:justify-start"><Link href="/signup" className="px-7 py-3.5 rounded-full bg-[#00A54F] text-white font-black text-[13px]">Get Started →</Link><Link href="#pricing" className="px-7 py-3.5 rounded-full bg-white/10 text-white font-black text-[13px] border border-white/10">View Pricing</Link></div></div>
          <div className="relative flex justify-center md:justify-end">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[360px] h-[360px] bg-[#00A54F]/20 blur-[50px] rounded-full" />
            <div className="relative w-[280px] h-[560px] bg-black rounded-[42px] p-[8px] shadow-[0_0_0_2px_rgba(255,255,255,0.15),0_25px_80px_rgba(0,0,0,0.6)] z-10"><div className="w-full h-full bg-white rounded-[34px] overflow-hidden flex flex-col"><div className="h-7 flex justify-center items-center"><div className="w-20 h-4 bg-black rounded-full" /></div><div className="px-4 py-2 flex justify-between border-b"><div className="flex gap-2 items-center"><div className="w-6 h-6 bg-[#00A54F] rounded-full flex items-center justify-center text-white text-[8px] font-black">GT</div><span className="font-black text-[11px] text-[#065F36]">GTSERVIZ</span></div><span>🔔</span></div><div className="mx-3 mt-3 bg-gradient-to-br from-[#065F36] to-[#00A54F] rounded-2xl p-4 text-white"><p className="text-[9px] opacity-70 font-bold">WALLET BALANCE</p><p className="text-[22px] font-black">₦2,450.00</p></div><div className="grid grid-cols-3 gap-2 p-3"><div className="bg-slate-50 rounded-xl p-3 text-center border text-[9px] font-bold">📱 Airtime</div><div className="bg-slate-50 rounded-xl p-3 text-center border text-[9px] font-bold">📶 Data</div><div className="bg-slate-50 rounded-xl p-3 text-center border text-[9px] font-bold">📺 TV</div><div className="bg-slate-50 rounded-xl p-3 text-center border text-[9px] font-bold">💡 Electric</div><div className="bg-slate-50 rounded-xl p-3 text-center border text-[9px] font-bold">🎓 Exam</div><div className="bg-slate-50 rounded-xl p-3 text-center border text-[9px] font-bold">💸 To Cash</div></div></div></div>
            <div className="absolute -right-6 top-[18%] z-20 float-anim hidden md:flex"><div className="px-4 py-2.5 bg-white rounded-xl shadow-xl border text-[11px] font-bold">📱 Airtime</div></div>
            <div className="absolute right-2 top-[38%] z-20 float-anim2 hidden md:flex"><div className="px-4 py-2.5 bg-white rounded-xl shadow-xl border text-[11px] font-bold">📶 Data</div></div>
            <div className="absolute -right-2 top-[58%] z-20 float-anim3 hidden md:flex"><div className="px-4 py-2.5 bg-white rounded-xl shadow-xl border text-[11px] font-bold">📺 Cable TV</div></div>
          </div>
        </div>
      </section>

      <section className="max-w-[1240px] mx-auto px-5 -mt-8 relative z-20 grid grid-cols-2 md:grid-cols-6 gap-3">{["Airtime","Data","Cable TV","Airtime to Cash","Electricity","Exam Pins"].map((t,i)=><div key={i} className="bg-white rounded-xl border p-4 text-center shadow-sm"><p className="font-black text-[12px]">{t}</p><p className="text-[10px] text-slate-500 mt-1">Instant delivery</p></div>)}</section>

      <section id="pricing" className="max-w-[1240px] mx-auto px-5 py-16 bg-[#eef5f0] rounded-[24px] mt-12"><p className="text-center text-[#00A54F] text-[11px] font-black">AFFORDABLE PRICING</p><h2 className="text-center text-[26px] font-black mt-2">Best rates for all services</h2><div className="grid md:grid-cols-3 gap-5 mt-10 max-w-[1000px] mx-auto"><div className="bg-white border rounded-2xl p-6"><h3 className="font-black">MTN Data</h3><p className="text-[28px] font-black text-[#065F36] mt-2">₦275 / 1GB</p><Link href="/signup" className="block mt-4 py-3 rounded-full bg-[#e6f6ec] text-center font-black text-[12px] text-[#065F36]">Buy Now</Link></div><div className="bg-[#061e14] text-white rounded-2xl p-6 md:scale-105 shadow-xl"><h3 className="font-black">Airtel Data</h3><p className="text-[28px] font-black text-[#00FF88] mt-2">₦280 / 1GB</p><Link href="/signup" className="block mt-4 py-3 rounded-full bg-[#00A54F] text-center font-black text-[12px]">Buy Now</Link></div><div className="bg-white border rounded-2xl p-6"><h3 className="font-black">Glo Data</h3><p className="text-[28px] font-black text-[#065F36] mt-2">₦270 / 1GB</p><Link href="/signup" className="block mt-4 py-3 rounded-full bg-[#e6f6ec] text-center font-black text-[12px] text-[#065F36]">Buy Now</Link></div></div></section>

      <section id="store" className="bg-white border-y py-16 mt-16"><div className="max-w-[1240px] mx-auto px-5"><p className="text-[#00A54F] text-[11px] font-black">GTSERVIZ STORE</p><h2 className="text-[24px] font-black mt-1">Digital Products Marketplace</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-8"><div className="border rounded-xl p-4 bg-[#f8faf8]">📦 MTN 1GB - ₦275</div><div className="border rounded-xl p-4 bg-[#f8faf8]">📺 DSTV Compact - ₦10,500</div><div className="border rounded-xl p-4 bg-[#f8faf8]">🎓 JAMB Pin - ₦4,200</div><div className="border rounded-xl p-4 bg-[#f8faf8]">💡 Electricity - From ₦1000</div></div></div></section>

      <section id="blog" className="max-w-[1240px] mx-auto px-5 py-16"><p className="text-[#00A54F] text-[11px] font-black">LATEST FROM BLOG</p><h2 className="text-[24px] font-black mt-1">Tips, News & Updates</h2><div className="grid md:grid-cols-3 gap-5 mt-8">{["How to start VTU business in 2026","Cheapest data plans this month","GTServiz API for developers"].map((t,i)=><div key={i} className="bg-white border rounded-xl p-5"><h4 className="font-black text-[14px]">{t}</h4><p className="text-[12px] text-slate-500 mt-2">Read more →</p></div>)}</div></section>

      <footer className="bg-[#0b1f35] text-white/60 py-10 text-center text-[12px]">© 2026 GTSERVIZ • 07012222025 • www.gtserviz.com</footer>
      <a href="https://wa.me/2347012222025" target="_blank" className="fixed bottom-6 right-6 z-[999] w-[60px] h-[60px] flex items-center justify-center"><div className="absolute w-full h-full pulse-ring rounded-full"></div><div className="relative w-[60px] h-[60px] bg-[#25D366] rounded-full flex items-center justify-center shadow-lg"><svg viewBox="0 0 32 32" className="w-[30px] h-[30px] fill-white"><path d="M16 2.9c-7.18 0-13 5.82-13 13 0 2.29.6 4.53 1.74 6.51L3 29l6.69-1.76A12.93 12.93 0 0016 29c7.18 0 13-5.82 13-13S23.18 2.9 16 2.9zm5.7 7.78c-.31-.16-1.85-.91-2.13-1.02-.29-.11-.5-.16-.7.16-.21.31-.81 1.02-.99 1.22-.18.21-.37.23-.68.08-.31-.16-1.32-.49-2.51-1.55-.93-.83-1.55-1.85-1.74-2.16-.18-.31-.02-.48.14-.64.14-.14.31-.37.47-.55.16-.18.21-.31.31-.52.1-.21.05-.39-.03-.55-.08-.16-.7-1.69-.96-2.31-.25-.61-.51-.53-.7-.54h-.6c-.21 0-.55.08-.83.39-.29.31-1.09 1.07-1.09 2.6s1.12 3.02 1.27 3.23c.16.21 2.2 3.36 5.33 4.71.75.32 1.33.51 1.78.66.75.24 1.43.2 1.97.12.6-.09 1.85-.76 2.11-1.49.26-.73.26-1.36.18-1.49-.08-.13-.29-.21-.6-.36z"/></svg></div></a>
    </div>
  );
}
